name: myenv  # Specify your environment name
channels:
  - conda-forge  # Conda-Forge is a community-driven channel with many useful packages
  - defaults
dependencies:
  - python=3.12  # Specify Python version (you can modify this)
  - dlib         # Include dlib for face recognition
  - pip          # Install pip if needed
  - pip:
      - streamlit
      - other-python-packages  # Add other Python dependencies if necessary
